### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by OPPOA113** [jiasenlu/YOLOv3.pytorch#1]
sh make.sh occur error:
c1: fatal error C1083: 无法打开源文件: “F:\Python\coding\pytorch\YOLOv3.pytorch                                        -master\misc\nms\src\nms_cuda.c”: No such file or directory
Traceback (most recent call last):
  File "F:\Python\Python35\lib\distutils\_msvccompiler.py", line 384, in compile
    self.spawn(args)
  File "F:\Python\Python35\lib\distutils\_msvccompiler.py", line 503, in spawn
    return super().spawn(cmd)
  File "F:\Python\Python35\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "F:\Python\Python35\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "F:\Python\Python35\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'D:\\Program Files (x86)\\Microsoft                                         Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\Python35\lib\site-packages\cffi\ffiplatform.py", line 51, in _                                        build
    dist.run_command('build_ext')
  File "F:\Python\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "F:\Python\Python35\lib\site-packages\setuptools\command\build_ext.py", l                                        ine 75, in run
    _build_ext.run(self)
  File "F:\Python\Python35\lib\site-packages\Cython\Distutils\old_build_ext.py",                                         line 186, in run
    _build_ext.build_ext.run(self)
  File "F:\Python\Python35\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "F:\Python\Python35\lib\site-packages\Cython\Distutils\old_build_ext.py",                                         line 194, in build_extensions
    self.build_extension(ext)
  File "F:\Python\Python35\lib\site-packages\setuptools\command\build_ext.py", l                                        ine 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "F:\Python\Python35\lib\distutils\command\build_ext.py", line 532, in bui                                        ld_extension
    depends=ext.depends)
  File "F:\Python\Python35\lib\distutils\_msvccompiler.py", line 386, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'D:\\Program Files (x86)\\Microsoft Visua                                        l Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "F:\Python\Python35\lib\site-packages\torch\utils\ffi\__init__.py", line                                         184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "F:\Python\Python35\lib\site-packages\torch\utils\ffi\__init__.py", line                                         108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "F:\Python\Python35\lib\site-packages\cffi\api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "F:\Python\Python35\lib\site-packages\cffi\recompiler.py", line 1520, in                                         recompile
    compiler_verbose, debug)
  File "F:\Python\Python35\lib\site-packages\cffi\ffiplatform.py", line 22, in c                                        ompile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "F:\Python\Python35\lib\site-packages\cffi\ffiplatform.py", line 58, in _                                        build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'D:\\Program Files (x86)\\Mi                                        crosoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status                                         2

what  should i do?

**Comment by jiasenlu** [comment]
This code is still in development. I'll try to add those file later. A star is appreciated while you ask the question :)
